site_name: testing

theme:
 name: material
 font:
  text: Lato

plugins:
  - offline
  
extra:
 generator: false
 homepage: https://docs.gog-games.com

extra_css:
 - stylesheets/extra.css
 
markdown_extensions:
 - admonition
 - pymdownx.details
 - pymdownx.superfences
